name               = "plutonium-proxy-worker"
main               = "index.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern   = "proxy.cdn.plutoniumnet.work/*"
zone_name = "plutoniumnet.work"

[vars]
ALLOWED_ORIGIN = "*.plutoniumnet.work,http://127.0.0.1:5500"
# HYPERBEAM_API_KEY — set via: wrangler secret put HYPERBEAM_API_KEY
